# Generated by Django 5.1 on 2024-09-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_date_added'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recipe',
            table='recipe',
        ),
    ]
