version: "3.8"

services:
  backend:
    build: ./backend
    container_name: drf_backend
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
